--- 
abstract: rich declarative non-hierarchical transactional objects
author: 
  - UR was built by the software development team at the Washington
build_requires: 
  Test::Fork: 0.02
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: UR
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.8.0
tests: t/*.t t/*/*.t t/*/*/*.t t/*/*/*/*.t
version: 0.9
